blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html
    about: Browse the Gradle IntelliJ Plugin documentation.
  - name: Getting Help
    url: https://plugins.jetbrains.com/docs/intellij/getting-help.html
    about: Check if you search for a help in plugin development.
